### ISSUE TITLE
review

### ISSUE THREAD

**Issue by wangii** [tmratwork/VOR-tmr#1]
issues:
- in `index.yaml`:
  - it's a good practice to avoid auto-generated index since it's not under our direct control.
  - it doesn't need an index if only query on one property. see document: https://cloud.google.com/appengine/docs/standard/go/datastore/indexes
  - I'd suggest to use Users table's row `key` as the userID, since 
    1.  it's automatically indexed and guaranteed to be unique.
    2. we saved a field.
- `myroot.go`:
  - it would be better if named as "main.go" or "app.go", give readers a clear idea it's the app entrance file.
  - Line 15: `var timeStamp time.Time` is unnecessary.
  - it would be simplified using GO's function syntax like below. (naming is such a challenging work that we'd better avoid)
```
func init() {
	http.HandleFunc("/user", func (w http.ResponseWriter, r *http.Request) {
// get a user record by userID
...
        })

	http.HandleFunc("/make", func (w http.ResponseWriter, r *http.Request) {
...
     })
}
``` 
- `structs.go`. 
  - I prefer to have one type struct in one file, instead of all struct definitions in one file.
  - it makes more sense to name `Users` as `User` since each instance of the struct represent a single user.
  - it's a good practice to put `DATASTORE_USERS` of the `constants.go` along with the struct `User` since they are logically associated and therefore better to be together.
- `utils.go` is good :)  even better if named as `auth.go`. 
- `iodatastore.go`:
  - UserGetById() has the naming consistency problem since the return value type is `*Users`.
  - in Line 28: in GO, people normally use `user := &User{}` to create a reference than using `new(User)`. There is a chance GO compiler to do more optimisation.
  - function `MakeSampleData` is obviously an internal usage thus better to begin with lower-case.

**Comment by tmratwork** [comment]
1) index.yaml
.. i understand your points (a) we should handle it manually, ignore the auto generated stuff at bottom and (b) can ignore indexes if only query on one property. does this mean my index.yaml files should be empty above the auto generated because i only query on one property?

2) readability
i feel my original version of showing all url's we handle in one place near top was very readable. your version has masses of code between the http.HandleFunc lines. my recollection of the stanford objective-c class was keep things in english (readable) in main block, then have methods to make possible the english in the main block. i made the change according to your suggestion, i assume you are correct.

3) readability part ii
my recollection as i try to understand the Vorail golang code is structs and constants are all over the place. i had to hunt for the file which contained constant VER. is there a special key combination i can click on a constant or struct to see where it is defined? that's why i put all my structs in one place, and all my constants in one place. 

4) readability part iii
glad you like "utils.go" since i got it from Vorail appengine golang code. not sure i like "utils.go" sounds very vague, catch-all type of a name. my understanding for readability, more specific name would be better. what does "auth.go" stand for?

done:
.. using userID for Users table's key 
.. changed "myroot.go" to "main.go"
.. removed line 15 "var timeStamp time.Time"
.. changed http.HandleFunc code organization according to Junior's view
.. changed struct "Users" to "User"
.. replaced "new(User)" with "&User{}"
.. changed "MakeSampleData" to "makeSampleData"

**Comment by wangii** [comment]
1. right. a good practice is to leave comments about a used index in this file when it's not necessary to add one.
2. you have a valid point. however, if following your way, there are two potential problems:
  - we'll have to give names to these functions. naming is never easy: 
> There are only two hard things in Computer Science: cache invalidation and naming things.  (https://martinfowler.com/bliki/TwoHardThings.html)
  - by having standalone functions, we won't have the urge to keep them small.
3. Vorail golang codes are not my best. there are lots of mistakes. to navigate to the definition of a symbol (constant, function), use cmd + click.
4. "auth" = authentication or authorisation.
